---
- name: Create ec2 instances for XAP mgt
  hosts: localhost
  connection: local
  gather_facts: False
  
  tasks:
  - name: create mgt machines
    local_action:
      module: ec2
      key_name: "{{key_name}}"
      region: "{{aws_region}}"
      group_id: "{{security_group}}"
      instance_type: "{{instance_type}}"
      image: "{{ami_id}}"
      wait: yes
      instance_tags:
        Name: lc-xap-mgt
      count: "{{mgt_instance_count}}"
    register: ec2

  - name: Add all instance public IPs to host group
    add_host: hostname={{ item.public_ip }} groups=mgthosts
    with_items: ec2.instances

  - name: Wait for SSH to come up
    wait_for: host={{ item.public_dns_name }} port=22 delay=60 timeout=320 state=started
    with_items: ec2.instances

  - name: Store private ips to pass as locators
    shell: echo -n {{ item.private_ip }}:4242, >> locators.txt
    with_items: ec2.instances

- hosts: mgthosts
  name: install XAP mgt play
  user: "{{user}}"
  gather_facts: true
  roles:
    - install_java
  environment:
    XAP_HOME: "{{home_dir}}/gshome"
    LOOKUPGROUPS: "{{lookup_groups}}"
    XAP_LOOKUP_GROUPS: "{{lookup_groups}}"
    GSA_JAVA_OPTIONS: "{{gsa_java_options}}"
    XAP_GSA_OPTIONS: "{{gsa_java_options}}"
    GSC_JAVA_OPTIONS: "{{gsc_java_options}}"
    XAP_GSC_OPTIONS: "{{gsc_java_options}}"
    GSM_JAVA_OPTIONS: "{{gsm_java_options}}"
    XAP_GSM_OPTIONS: "{{gsm_java_options}}"
    LUS_JAVA_OPTIONS: "{{lus_java_options}}"
    XAP_LUS_OPTIONS: "{{lus_java_options}}"
    EXT_JAVA_OPTIONS: "{{ext_java_options}}"
    INTERFACE_NAME: "{{interface_name}}"
    MGT_GLOBAL_LUS_CNT: "{{mgt_global_lus_cnt}}"
    MGT_LUS_CNT: "{{mgt_lus_cnt}}"
    MGT_GLOBAL_GSM_CNT: "{{mgt_global_gsm_cnt}}"
    MGT_GSM_CNT: "{{mgt_gsm_cnt}}"
    MGT_GSC_CNT: "{{mgt_gsc_cnt}}"
  tasks:
  - name: fetch XAP
    get_url: url="{{xap_url}}" dest={{home_dir}} mode=0777
  - name: get zip file name
    shell: "ls gigaspaces*.zip"
    args:
      chdir: "{{home_dir}}"
    register: zip_name
  - name: exctract XAP
    unarchive: src="{{home_dir}}/{{zip_name.stdout}}" dest={{home_dir}} mode=0777 copy=no
  - name: delete zip
    command: "rm {{home_dir}}/{{zip_name.stdout}}"
  - name: rename XAP home folder
    shell: "mv `ls -d {{home_dir}}/gigaspaces*premium*` gshome"
    args:
      chdir: "{{home_dir}}"
  - name: copy locators file
    copy: src=locators.txt dest={{home_dir}} owner={{user}} mode=0777
  - name: copy env script
    copy: src=files/env.sh dest={{home_dir}} owner={{user}} mode=0777
  - name: copy run script
    copy: src=files/run-mgt.sh dest={{home_dir}} owner={{user}} mode=0777  
  - name: deploy XAP mgt
    shell: "nohup ./run-mgt.sh {{lookup_groups}} {{home_dir}}/gshome &"
    args:
      chdir: "{{home_dir}}"
